apiVersion: apps/v1
kind: Deployment
metadata:
  name: stns-deploy
  labels:
    app: stns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stns
  template:
    metadata:
      labels:
        app: stns
    spec:
      volumes:
        # Build script: builder.sh
        - name: builder-assets-volume
          configMap:
            name: builder-config
        # Share git sources between git-sync and builder
        - name: git-source-volume
          emptyDir: {}
        # Share build config 'cdsl.toml' between builder and stns-server
        - name: config-volume
          emptyDir: {}
        # SSH Praivate Key
        - name: ssh-key-volume
          secret:
            secretName: git-sync-ssh-key
            items:
              - key: id_ed25519
                path: ssh
                mode: 0600
      securityContext:
        fsGroup: 65533
      shareProcessNamespace: true
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.4
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
            requests:
              memory: 32Mi
              cpu: "0.1"
          args:
            - "-ssh"
            - "-repo=git@github.com:cdsl-research/stns-config"
            - "-branch=master"
            - "-depth=1"
            - "-ssh-known-hosts=false"
            - "-wait=30"
          volumeMounts:
            - name: git-source-volume
              mountPath: /tmp/git
            - name: ssh-key-volume
              mountPath: /etc/git-secret
          securityContext:
            runAsUser: 65533

        - name: builder
          image: python:3.9-alpine
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
            requests:
              memory: 32Mi
              cpu: "0.1"
          command: ["/bin/sh", "/builder/build.sh"]
          volumeMounts:
            - name: builder-assets-volume
              mountPath: /builder
            - name: git-source-volume
              mountPath: /src
            - name: config-volume
              mountPath: /config

        - name: stns-server
          image: ghcr.io/cdsl-research/stns-container:master-3d7b515
          args: ["--config", "/config/cdsl.toml", "server"]
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
            requests:
              memory: 32Mi
              cpu: "0.1"
          ports:
            - containerPort: 1104
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          readinessProbe:
            httpGet:
              port: 1104
              path: /
            successThreshold: 1
            failureThreshold: 1
            periodSeconds: 1
