apiVersion: apps/v1
kind: Deployment
metadata:
  name: stns-deploy
  labels:
    app: stns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stns
  template:
    metadata:
      labels:
        app: stns
    spec:
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.4
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: "0.1"
          args:
            - "-ssh"
            - "-repo=git@github.com:cdsl-research/stns-config"
            - "-root=/tmp/git"
            # - "--sync-hook-command=xxx"
            - "-branch=master"
            - "-depth=1"
            - "-ssh-key-file=/etc/git-secret/ssh/id_ed25519"
            - "-ssh-known-hosts=false"
            - "-wait=60"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: ssh-key-volume
              mountPath: /etc/git-secret/ssh
        # - name: stns-server
        #   image: ghcr.io/cdsl-research/stns-container:master
        #   ports:
        #     - containerPort: 1104
        #   volumeMounts:
        #     - name: config-volume
        #       mountPath: /config
        #       readOnly: true
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: ssh-key-volume
          secret:
            secretName: git-sync-ssh-key
            items:
              - key: id_ed25519
                path: id_ed25519
                mode: 0600