name: Image Build

on:
  push:
    branches: master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:

      - name: Log in container registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u tomoyk --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cdsl-research/stns-container/stns-server:v0.1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
